-- *************************************************************************************************
-- This script creates all of the database objects (tables, sequences, etc) for the database
-- *************************************************************************************************

BEGIN;

-- CREATE statements go here

CREATE SEQUENCE seq_student_id;
CREATE TABLE student_profile (

	student_id integer NOT NULL DEFAULT nextval('seq_student_id'),
	firstName VARCHAR(20),
	lastName VARCHAR(20),
	username VARCHAR(32) NOT NULL,
	cohort VARCHAR(25),
	courseLanguage VARCHAR(20),
	streetAddress VARCHAR(40),
	city VARCHAR(40),
	state VARCHAR(2),
	postCode integer,
	email VARCHAR(40),
	phoneNumber VARCHAR(20),
	summary VARCHAR(1000),
	careerExperience VARCHAR(50),
	interests VARCHAR(60),
	academicBackground VARCHAR(40),
	skills VARCHAR(50),

	CONSTRAINT pk_student_profile_username PRIMARY KEY (username)
);

CREATE SEQUENCE seq_employer_id;
CREATE TABLE employer (
	employer_id integer NOT NULL DEFAULT nextval('seq_employer_id'),
	username VARCHAR(32) NOT NULL,
	company_name VARCHAR(50),
	CONSTRAINT pk_employer_employer_id PRIMARY KEY (employer_id)
);

CREATE SEQUENCE seq_staff_id;
CREATE TABLE staff (
	staff_id integer NOT NULL DEFAULT nextval('seq_staff_id'),
	username VARCHAR(32) NOT NULL,
	CONSTRAINT pk_staff_staff_id PRIMARY KEY (staff_id)
);

CREATE TABLE app_user (
  username varchar(32) NOT NULL,
  password varchar(32) NOT NULL,
  user_type varchar(32) NOT NULL,
  salt varchar(256) NOT NULL,	
  CONSTRAINT pk_app_user_username PRIMARY KEY (username)
);

CREATE SEQUENCE seq_project_id;
CREATE TABLE project (
	project_id integer NOT NULL DEFAULT nextval('seq_project_id'),
	username varchar(32) NOT NULL,
	projectName varchar(50),
	description varchar(5000),
	projectType varchar(20),
	CONSTRAINT pk_project_project_id PRIMARY KEY (project_id),
	CONSTRAINT fk_project_student_profile FOREIGN KEY (username) REFERENCES student_profile (username)
);




insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Jeremy', 'Reyes', 'student0', 'cohort04', '.net', '2 Fisk Junction', 'Salt Lake City', 'UT', '84152', 'jreyes0@timesonline.co.uk', '(801)287-5643', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.', 'Senior Quality Engineer', 'Database Management', 'Doctoral','Focus');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Donald', 'Wells', 'student1', 'cohort04', 'java', '090 Blaine Park', 'Houston', 'TX', '77223', 'dwells1@naver.com', '(713)883-8964', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'Legal Assistant', 'Database Management', 'Doctoral','Learner');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Sara', 'Hunter', 'student2', 'cohort04', '.net', '18174 Dennis Junction', 'Colorado Springs', 'CO', '80930', 'shunter2@bbc.co.uk', '(719)200-9664', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Assistant Professor', 'Artificial intelligence', 'Doctoral','Restorative');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Laura', 'Sullivan', 'student3', 'cohort04', '.net', '8466 Morrow Place', 'Roanoke', 'VA', '24014', 'lsullivan3@biblegateway.com', '(540)869-3898', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'Physical Therapy Assistant', 'Artificial intelligence', 'Doctoral','Achiever');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Howard', 'Lewis', 'student4', 'cohort04', 'java', '2047 Scott Road', 'Winston Salem', 'NC', '27110', 'hlewis4@ftc.gov', '(336)354-3142', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.', 'Computer Systems Analyst III', 'Architecture', 'Bachelor''s degree','Activator');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Dorothy', 'Lynch', 'student5', 'cohort04', '.net', '90 Stuart Street', 'Jacksonville', 'FL', '32255', 'dlynch5@state.gov', '(904)883-7633', 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.', 'Senior Sales Associate', 'Graphics', 'High school','Analytical');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Frances', 'Gardner', 'student6', 'cohort04', 'java', '914 Caliangt Street', 'Atlanta', 'GA', '30358', 'fgardner6@nymag.com', '(404)922-3120', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.', 'Web Designer I', 'Architecture', 'Bachelor''s degree','Belief');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Matt', 'Robertson', 'matt_007', 'cohort04', 'java', '05816 Melrose Plaza', 'Tacoma', 'WA', '98417', 'probertson7@bizjournals.com', '(253)818-2289', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.', 'Accounting Assistant IV', 'Artificial intelligence', 'High school','Command');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Jerry', 'Woods', 'student8', 'cohort04', '.net', '6 Oriole Terrace', 'Rockford', 'IL', '61110', 'jwoods8@marketwatch.com', '(815)217-2290', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.', 'Account Coordinator', 'Distributed systems', 'Bachelor''s degree','Communication');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Ashley', 'Matthews', 'student9', 'cohort04', 'java', '880 Mallory Junction', 'Carson City', 'NV', '89706', 'amatthews9@nasa.gov', '(775)365-2426', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.', 'VP Marketing', 'Graphics', 'Master''s degree','Competition');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Vineeta', 'Butler', 'vineeta0', 'cohort04', 'java', '961 Carpenter Hill', 'Irvine', 'CA', '92612', 'jbutlera@dailymotion.com', '(510)207-4925', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.', 'Human Resources Assistant I', 'Database Management', 'Master''s degree','Connectedness');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Brandon', 'Frazier', 'student11', 'cohort04', 'java', '3153 Crest Line Point', 'Reno', 'NV', '89595', 'bfrazierb@psu.edu', '(775)787-1152', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'Assistant Professor', 'Technology', 'Doctoral','Deliberative');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Denise', 'Wheeler', 'student12', 'cohort04', '.net', '11210 Golf Course Pass', 'San Francisco', 'CA', '94154', 'dwheelerc@comsenz.com', '(415)803-4813', 'Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Systems Administrator IV', 'Networking', 'Bachelor''s degree','Developer');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Scott', 'George', 'student13', 'cohort04', '.net', '94841 Hollow Ridge Trail', 'Portsmouth', 'NH', '00214', 'sgeorged@weibo.com', '(603)627-7673', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'Analog Circuit Design manager', 'Database Management', 'Doctoral','Discipline');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Phyllis', 'Long', 'student14', 'cohort04', '.net', '7 Tony Place', 'Memphis', 'TN', '38136', 'plonge@drupal.org', '(901)705-0081', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Account Coordinator', 'Technology', 'High school','Empathy');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Joan', 'Edwards', 'student15', 'cohort04', '.net', '28951 Corben Pass', 'Charlottesville', 'VA', '22903', 'jedwardsf@bbc.co.uk', '(434)486-5158', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.', 'Design Engineer', 'Graphics', 'Master''s degree','Focus');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Victor', 'Watkins', 'student16', 'cohort04', 'java', '78 Park Meadow Lane', 'Lexington', 'KY', '40576', 'vwatkinsg@is.gd', '(859)640-3010', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.', 'Business Systems Development Analyst', 'Architecture', 'Master''s degree','Harmony');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Kathleen', 'Lynch', 'student17', 'cohort04', 'java', '846 Eastlawn Way', 'Washington', 'DC', '20310', 'klynchh@fotki.com', '(202)533-9102', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Quality Engineer', 'Security', 'High school','Includer');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Katherine', 'Evans', 'student18', 'cohort04', '.net', '74811 Annamark Hill', 'Kansas City', 'MO', '64190', 'kevansi@seattletimes.com', '(816)896-7928', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.', 'Nurse', 'Artificial intelligence', 'Master''s degree','Individualization');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Bobby', 'Kelley', 'student19', 'cohort04', '.net', '47754 School Plaza', 'Mc Keesport', 'PA', '15134', 'bkelleyj@bbc.co.uk', '(412)859-8207', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'Health Coach I', 'Graphics', 'Bachelor''s degree','Input');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Pamela', 'Collins', 'student20', 'cohort04', 'java', '54 Canary Trail', 'Richmond', 'VA', '23285', 'pcollinsk@blogtalkradio.com', '(804)243-6486', 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Paralegal', 'Database Management', 'Master''s degree','Learner');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Helen', 'Wright', 'student21', 'cohort04', '.net', '5 Eastlawn Parkway', 'Pensacola', 'FL', '32595', 'hwrightl@prweb.com', '(850)525-9047', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.', 'Biostatistician IV', 'Architecture', 'High school','Maximizer');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Donald', 'Cruz', 'student22', 'cohort04', 'java', '37 Sherman Court', 'New Hyde Park', 'NY', '11044', 'dcruzm@usa.gov', '(516)172-3700', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 'Help Desk Technician', 'Networking', 'Bachelor''s degree','Positivity');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Louis', 'Mcdonald', 'student23', 'cohort04', '.net', '3601 Brown Pass', 'Tallahassee', 'FL', '32399', 'lmcdonaldn@xinhuanet.com', '(850)297-4893', 'Nullam molestie nibh in lectus.', 'Marketing Manager', 'Technology', 'Bachelor''s degree','Responsibility');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Joyce', 'Bailey', 'student24', 'cohort04', 'java', '4884 Autumn Leaf Circle', 'Nashville', 'TN', '37240', 'jbaileyo@telegraph.co.uk', '(615)878-3360', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.', 'Librarian', 'Artificial intelligence', 'Master''s degree','Restorative');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Julie', 'Hart', 'student25', 'cohort04', '.net', '23 Ronald Regan Street', 'Littleton', 'CO', '80161', 'jhartp@yelp.com', '(720)591-8702', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Nurse', 'Technology', 'Doctoral','Learner');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Maria', 'Rice', 'student26', 'cohort04', '.net', '22271 Ludington Parkway', 'Mountain View', 'CA', '94042', 'mriceq@wufoo.com', '(650)324-9886', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Business Systems Development Analyst', 'Distributed systems', 'High school','Self-Assurance');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Jeffrey', 'Long', 'student27', 'cohort04', '.net', '4 Towne Circle', 'Oceanside', 'CA', '92056', 'jlongr@newsvine.com', '(858)250-4077', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Account Representative II', 'Artificial intelligence', 'Bachelor''s degree','Significance');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Nicholas', 'Fowler', 'student28', 'cohort04', '.net', '6 Lerdahl Avenue', 'Bryan', 'TX', '77806', 'nfowlers@diigo.com', '(979)585-6939', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'VP Sales', 'Database Management', 'High school','Strategic');
insert into student_profile (firstName, lastName, username, cohort, courseLanguage, streetAddress, city, state, postCode, email, phoneNumber, summary, careerExperience, interests, academicBackground,skills) values ('Julie', 'Gonzalez', 'student29', 'cohort04', '.net', '17 Killdeer Place', 'Long Beach', 'CA', '90847', 'jgonzalezt@redcross.org', '(562)883-1454', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.', 'Recruiter', 'Security', 'Bachelor''s degree','Win over others');


INSERT INTO app_user (username, password, user_type, salt) VALUES ('admin1', 'qAzSTYTn8AfMIvnOCq8F9A==', 'staff', 'vrcuHHA9sIK9Od2c9zwOQuZMmwj81vzvhAyGzcLb2YGp2KH1LqI2wLiUJb8Wpvg6AfMfHaaAgjwQFctw0xQug74T42jgZ6zMwHyYDAGuCywqE7RuP0iVDV6Fo++cGYwtgUiJSiG4RW1LUiOG/IWF3MEejN5K/1di/JuwM/ADh+s=');
INSERT INTO app_user (username, password, user_type, salt) VALUES ('student0', 'AqHSoc2qcabweuOcKOdAAw==', 'student', 'gDDO6X6VbBy/AHFKdwYaTQ0AY8jK9OZImLAWv0dI7L8RROIA5okveQ48ao0iNfRF4LQJGhIJ/YrdTVHQxfOpu85lEgsZOsOLUajxAPPYU50ZgrGkhc2174zVHqG1B20ifdc62mVp7ZAEtyRWD2ud0utAKAT7OplYgjEJpxMR8KY=');
INSERT INTO app_user (username, password, user_type, salt) VALUES ('employer1', '0FyxyRh0CgxNntzVcr/B/g==', 'employer', 'Ax18v2C1JC82E0srDgZfszVsSKX5hjPDWEr8YeqWL+rq4gjFqOH4ZYv0MYdlb71VdTIRVB/NZrIU6ofH+7u60d6870kzi2M3F7rjMbUSuSZTBapyu/0HdcxvWwk2uak0ojqxRmOEGyPrvUEZuK+/TMACqnTAdhXyivxAn42I1TQ=');
INSERT INTO app_user (username, password, user_type, salt) VALUES ('matt_007', '6/TuOJdyDo3Hx8x6JC+Fhg==', 'student', 'u7WxBAeWD6W7x5Z0VIexGhQS0NKPm9Y34N5cGB5gVEG03+doKAlDeJXntLIb/uDGP6ke4HxzjtC8Sj5EL/lN+RJAhT4wbI9+g26H1aOKKxLFPusP647zZr1TyiIWJ0dx/ikcDE1gXiaurv0qiQ3TVekaudf35YqAM4JErVze0AQ=');
INSERT INTO app_user (username, password, user_type, salt) VALUES ('vineeta0', 'piLWf3wYgdGhKC7aXE+tOA==', 'student', 'fsuYJsYj43PxbvmNIWo5Va8WlS32lcqbZqxgAFX6a/Mu9m6lDEnk20IuWMK+9pA5lzQj/kV7unnlBNmE3NCfdivsBEtnRwC3mEZeKI0vU1ozDFnnjT2B2+bqTjDQsxs1otlB6ieJPs3uP7fw9Os8jYdvOnjU/7vGxm6Eealztik=');



insert into project (username, projectName, description, projectType) values ('student0', 'Latlux', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 'Group');
insert into project (username, projectName, description, projectType) values ('student0', 'Alphazap', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst.', 'Individual');
insert into project (username, projectName, description, projectType) values ('student0', 'Redhold', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Group');
insert into project (username, projectName, description, projectType) values ('student0', 'Ventosanzap', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Individual');
insert into project (username, projectName, description, projectType) values ('student0', 'Lotstring', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'Group');
insert into project (username, projectName, description, projectType) values ('student1', 'Transcof', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Group');
insert into project (username, projectName, description, projectType) values ('student1', 'Cardify', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.', 'Individual');
insert into project (username, projectName, description, projectType) values ('student1', 'Tresom', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.', 'Individual');
insert into project (username, projectName, description, projectType) values ('student3', 'Voyatouch', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.', 'Individual');
insert into project (username, projectName, description, projectType) values ('student4', 'Pannier', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Group');
insert into project (username, projectName, description, projectType) values ('student5', 'Daltfresh', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Individual');
insert into project (username, projectName, description, projectType) values ('student6', 'Span', 'Proin eu mi.', 'Individual');
insert into project (username, projectName, description, projectType) values ('student3', 'Sonair', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Group');
insert into project (username, projectName, description, projectType) values ('student8', 'Namfix', 'Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'Group');
insert into project (username, projectName, description, projectType) values ('student9', 'Bamity', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum.', 'Group');
insert into project (username, projectName, description, projectType) values ('student9', 'Biodex', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Individual');
insert into project (username, projectName, description, projectType) values ('matt_007', 'Temp', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.', 'Group');
insert into project (username, projectName, description, projectType) values ('matt_007', 'Prodder', 'Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Group');
insert into project (username, projectName, description, projectType) values ('matt_007', 'Rank', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 'Individual');
insert into project (username, projectName, description, projectType) values ('matt_007', 'Cardguard', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'Group');
insert into project (username, projectName, description, projectType) values ('vineeta0', 'Overhold', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.', 'Group');
insert into project (username, projectName, description, projectType) values ('vineeta0', 'Flowdesk', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Group');
insert into project (username, projectName, description, projectType) values ('vineeta0', 'Mat Lam Tam', 'Maecenas pulvinar lobortis est.', 'Individual');
insert into project (username, projectName, description, projectType) values ('vineeta0', 'Temp', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'Group');
insert into project (username, projectName, description, projectType) values ('student19', 'Alpha', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor.', 'Individual');
insert into project (username, projectName, description, projectType) values ('student20', 'Greenlam', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.', 'Group');
insert into project (username, projectName, description, projectType) values ('student21', 'Bytecard', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Group');
insert into project (username, projectName, description, projectType) values ('student22', 'Y-find', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.', 'Group');
insert into project (username, projectName, description, projectType) values ('student23', 'Duobam', 'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Group');
insert into project (username, projectName, description, projectType) values ('student24', 'Konklab', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.', 'Individual');


COMMIT;